'use client';
import {useEffect,useMemo,useState} from 'react';
type Model={id:string;name?:string};
const shortName=(id:string)=>{let raw=id.split('/').pop()||id;raw=raw.replace(/\.(gguf|safetensors)$/i,'').replace(/[-_]/g,' ');raw=raw.replace(/\b(instruct|chat|it|gguf|awq|fp16|q[0-9][a-z0-9]*|latest|free)\b.*$/i,'').trim();const words=raw.split(/\s+/).filter(Boolean);return (words.slice(0,5).join(' ')||id).slice(0,34)};
export default function Home(){const [models,setModels]=useState<Model[]>([]);const [model,setModel]=useState('');const [prompt,setPrompt]=useState('');const [reply,setReply]=useState('');const [loading,setLoading]=useState(false);const [tab,setTab]=useState('Chat');
useEffect(()=>{const load=async()=>{try{const r=await fetch('/api/models',{cache:'no-store'});const d=await r.json();setModels(d.models||[]);setModel(x=>x||d.models?.[0]?.id||'')}catch{}};load();const t=setInterval(load,60000);return()=>clearInterval(t)},[]);
const selected=useMemo(()=>models.find(m=>m.id===model),[models,model]);
async function send(){if(!prompt.trim()||!model||loading)return;setLoading(true);setReply('');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'user',content:prompt}]})});const d=await r.json();setReply(d.content||d.error||'No response.')}catch{setReply('Something went wrong.')}finally{setLoading(false)}}
return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"/>NextRouter</div><nav className="nav">{['Chat','Models'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><div className="sidebar-foot">A focused workspace for AI.</div></aside><main className="main"><header className="topbar"><div style={{fontSize:13,color:'#8791a5'}}>{tab}</div><div className="status"><span className="dot"/>Systems operational</div></header><section className="content">{tab==='Chat'?<><div className="hero"><div className="eyebrow">Your AI workspace</div><h1>Think faster.<br/><span style={{color:'#60a5fa'}}>Build anything.</span></h1><p>A clean, fast interface for exploring powerful AI models from one place.</p></div><div className="chat"><div className="chat-head"><div style={{fontSize:13,color:'#8791a5'}}>Model</div><select className="model-select" value={model} onChange={e=>setModel(e.target.value)}>{models.length?models.slice(0,80).map(m=><option key={m.id} value={m.id}>{shortName(m.id)}</option>):<option>Loading models...</option>}</select></div><div className="chat-body">{reply?<div className="empty" style={{maxWidth:680,textAlign:'left'}}><div className="eyebrow">Response</div><p style={{whiteSpace:'pre-wrap',color:'#cbd5e1',fontSize:14}}>{reply}</p></div>:<div className="empty"><div className="empty-icon">✦</div><h2>Start a conversation</h2><p>Choose a model and send a message. Your conversation starts here.</p></div>}</div><div className="composer"><div className="composer-row"><input value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Message NextRouter..."/><button className="send" onClick={send}>{loading?'...':'Send'}</button></div></div></div></>:<div><div className="hero" style={{textAlign:'left',marginLeft:0}}><div className="eyebrow">Live catalog</div><h1 style={{fontSize:48}}>Models.</h1><p>Models refresh automatically so the catalog stays current.</p></div><div className="grid">{models.map(m=><div className="card" key={m.id}><div className="card-name" title={m.id}>{shortName(m.id)}</div><div className="card-meta">Available now</div><span className="badge">Ready</span></div>)}</div></div>}</section></main></div>}
